// Package tlsutil builds mutual-TLS configs from the material generated by
// `make certs`: a cluster CA plus a shared service certificate valid for all
// component hostnames. Nothing connects without these files present.
package tlsutil

import (
	"crypto/tls"
	"crypto/x509"
	"fmt"
	"os"

	"github.com/sohamghodake/ironwork/internal/config"
)

// Server returns a TLS config that presents the service certificate and
// requires + verifies a client certificate signed by the cluster CA.
func Server(p config.TLSPaths) (*tls.Config, error) {
	cert, pool, err := load(p)
	if err != nil {
		return nil, err
	}
	return &tls.Config{
		MinVersion:   tls.VersionTLS13,
		Certificates: []tls.Certificate{cert},
		ClientAuth:   tls.RequireAndVerifyClientCert,
		ClientCAs:    pool,
	}, nil
}

// Client returns a TLS config that presents the service certificate and
// verifies the server against the cluster CA.
func Client(p config.TLSPaths) (*tls.Config, error) {
	cert, pool, err := load(p)
	if err != nil {
		return nil, err
	}
	return &tls.Config{
		MinVersion:   tls.VersionTLS13,
		Certificates: []tls.Certificate{cert},
		RootCAs:      pool,
	}, nil
}

func load(p config.TLSPaths) (tls.Certificate, *x509.CertPool, error) {
	cert, err := tls.LoadX509KeyPair(p.CertFile, p.KeyFile)
	if err != nil {
		return tls.Certificate{}, nil, fmt.Errorf("tlsutil: load key pair (did you run `make certs`?): %w", err)
	}
	caPEM, err := os.ReadFile(p.CAFile)
	if err != nil {
		return tls.Certificate{}, nil, fmt.Errorf("tlsutil: read CA (did you run `make certs`?): %w", err)
	}
	pool := x509.NewCertPool()
	if !pool.AppendCertsFromPEM(caPEM) {
		return tls.Certificate{}, nil, fmt.Errorf("tlsutil: no certificates parsed from %s", p.CAFile)
	}
	return cert, pool, nil
}
