// Package config loads component configuration from IRONWORK_* environment
// variables via viper, with defaults suited to local compose runs.
package config

import (
	"fmt"
	"strings"

	"github.com/spf13/viper"
)

// Config holds settings shared by all Ironwork components; each component
// reads only the fields relevant to it.
type Config struct {
	// Component kind: gateway, scheduler, worker, statemanager, observer, migrate.
	Component string
	// Instance is this process's unique name in the cluster (e.g. scheduler-2).
	Instance string
	// HTTPAddr is the REST listen address (gateway).
	HTTPAddr string
	// GRPCAddr is the gRPC listen address (all long-running services).
	GRPCAddr string
	// DBDSN is the Postgres connection string (migrate, observer).
	DBDSN string
	// ObserverAddr is the observer's gRPC address (gateway).
	ObserverAddr string
	// Targets maps instance name -> gRPC address for observer fan-out checks,
	// parsed from "name=addr,name=addr" form.
	Targets map[string]string
	// Workers maps instance name -> gRPC address for gateway job dispatch
	// (Phase 1; the scheduler takes over placement in Phase 2). Same format
	// as Targets.
	Workers map[string]string
	// Capacity is the max number of jobs a worker executes concurrently.
	Capacity int
	LogLevel string
	TLS      TLSPaths
}

// TLSPaths locates the mTLS material generated by `make certs`.
type TLSPaths struct {
	CertFile string
	KeyFile  string
	CAFile   string
}

// Load reads configuration for the given component kind from the environment.
func Load(component string) (*Config, error) {
	v := viper.New()
	v.SetEnvPrefix("IRONWORK")
	v.SetEnvKeyReplacer(strings.NewReplacer(".", "_"))
	v.AutomaticEnv()

	v.SetDefault("instance", component)
	v.SetDefault("http_addr", ":8080")
	v.SetDefault("grpc_addr", ":9443")
	// Host port 5433 matches the compose mapping for postgres-primary.
	v.SetDefault("db_dsn", "postgres://ironwork:ironwork@localhost:5433/ironwork?sslmode=disable")
	v.SetDefault("observer_addr", "observer:9443")
	v.SetDefault("targets", "")
	v.SetDefault("workers", "")
	v.SetDefault("capacity", 4)
	v.SetDefault("log_level", "info")
	v.SetDefault("tls.cert_file", "certs/service.pem")
	v.SetDefault("tls.key_file", "certs/service-key.pem")
	v.SetDefault("tls.ca_file", "certs/ca.pem")

	targets, err := parseTargets(v.GetString("targets"))
	if err != nil {
		return nil, fmt.Errorf("config: invalid IRONWORK_TARGETS: %w", err)
	}
	workers, err := parseTargets(v.GetString("workers"))
	if err != nil {
		return nil, fmt.Errorf("config: invalid IRONWORK_WORKERS: %w", err)
	}

	return &Config{
		Component:    component,
		Instance:     v.GetString("instance"),
		HTTPAddr:     v.GetString("http_addr"),
		GRPCAddr:     v.GetString("grpc_addr"),
		DBDSN:        v.GetString("db_dsn"),
		ObserverAddr: v.GetString("observer_addr"),
		Targets:      targets,
		Workers:      workers,
		Capacity:     v.GetInt("capacity"),
		LogLevel:     v.GetString("log_level"),
		TLS: TLSPaths{
			CertFile: v.GetString("tls.cert_file"),
			KeyFile:  v.GetString("tls.key_file"),
			CAFile:   v.GetString("tls.ca_file"),
		},
	}, nil
}

func parseTargets(s string) (map[string]string, error) {
	targets := map[string]string{}
	for _, pair := range strings.Split(s, ",") {
		pair = strings.TrimSpace(pair)
		if pair == "" {
			continue
		}
		name, addr, ok := strings.Cut(pair, "=")
		if !ok || name == "" || addr == "" {
			return nil, fmt.Errorf("malformed pair %q, want name=host:port", pair)
		}
		targets[name] = addr
	}
	return targets, nil
}
